// some of them are missing from the map,
// I've commented them out
export const eu = [
    "Austria",
    // "Belgium",
    "Bulgaria",
    "Croatia",
    // "Republic of Cyprus",
    "CzechRepublic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    // additions
    "Norway",
    "Switzerland",
];
